version: '3'
services:
  kinto:
    container_name: kinto
    image: kinto/kinto-server
    ports:
      - 8888:8888
    environment:
      - KINTO_USERID_HMAC_SECRET=secret
      - KINTO_BATCH_MAX_REQUESTS=200
      - KINTO_STORAGE_BACKEND=kinto.core.storage.postgresql
      - KINTO_STORAGE_URL=postgresql://postgres:secret@database:5432/kinto
    depends_on:
      - database
  database:
    container_name: database
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web:
    container_name: web
    build: web
    ports:
      - 80:80
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 81:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@foo.bar
      - PGADMIN_DEFAULT_PASSWORD=pass
    depends_on:
      - kinto
#   cloudbeaver:
#     container_name: cloudbeaver
#     image: dbeaver/cloudbeaver:latest
#     ports:
#       - 8080:8978
#     volumes:
#       - cloudbeaver:/opt/cloudbeaver/workspace
# volumes:
#   cloudbeaver:
    


    
    